import timingsJson from './story-timings.json'

// Sentence-level narration timings, generated by
// scripts/generate-story-narration.ts alongside the MP3s. Keyed by section id.
// Sections without an entry fall back to plain markdown rendering in the
// player (so a fresh clone with an empty story-timings.json still builds
// and renders fine - just without sentence highlighting).

export type SentenceTiming = { md: string; start: number; end: number }
export type SectionTimings = { paragraphs: SentenceTiming[][] }

export const STORY_TIMINGS: Record<string, SectionTimings> =
  timingsJson as Record<string, SectionTimings>

/** Flat sentence list for a section, in narration order. */
export function flatSentences(t: SectionTimings): SentenceTiming[] {
  return t.paragraphs.flat()
}
